# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 680)
        MainWindow.setMinimumSize(QtCore.QSize(900, 680))
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #141417, stop:1 #1e1e22);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 1px solid #333;\n"
"    border-radius: 12px;\n"
"    margin-top: 12px;\n"
"    padding-top: 10px;\n"
"    background-color: #1e1e22;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 8px;\n"
"    color: #00ff88;\n"
"    background-color: #1e1e22;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #00ff88;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit, QSpinBox {\n"
"    background-color: #2d2d30;\n"
"    border: 2px solid #333;\n"
"    border-radius: 10px;\n"
"    padding: 12px;\n"
"    color: #ffffff;\n"
"    font-size: 13px;\n"
"    selection-background-color: #00ff88;\n"
"}\n"
"\n"
"QLineEdit:focus, QSpinBox:focus {\n"
"    border: 2px solid #00ff88;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #00ff88;\n"
"    color: #000;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 12px 24px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00cc70;\n"
"}\n"
"\n"
"QPushButton#startButton {\n"
"    background-color: #00d0ff;\n"
"    font-size: 16px;\n"
"    padding: 16px 40px;\n"
"}\n"
"\n"
"QPushButton#startButton:hover {\n"
"    background-color: #00a8cc;\n"
"}\n"
"\n"
"QPushButton#stopButton {\n"
"    background-color: #ff2d55;\n"
"    font-size: 16px;\n"
"    padding: 16px 40px;\n"
"}\n"
"\n"
"QPushButton#stopButton:hover {\n"
"    background-color: #e01e45;\n"
"}\n"
"\n"
"QPushButton#testTokenButton, QPushButton#testChannelButton {\n"
"    background-color: #333;\n"
"    color: #00ff88;\n"
"}\n"
"\n"
"QLCDNumber {\n"
"    background-color: #0f0f12;\n"
"    color: #00ff88;\n"
"    border: 2px solid #333;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QTextEdit#logDisplay {\n"
"    background-color: #0f0f12;\n"
"    color: #00ff88;\n"
"    border: 1px solid #333;\n"
"    border-radius: 12px;\n"
"    font-family: Consolas, monospace;\n"
"    font-size: 12px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        self.mainLayout.setSpacing(15)
        self.mainLayout.setObjectName("mainLayout")
        self.groupToken = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupToken.setObjectName("groupToken")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.groupToken)
        self.hboxlayout.setObjectName("hboxlayout")
        self.botTokenInput = QtWidgets.QLineEdit(parent=self.groupToken)
        self.botTokenInput.setObjectName("botTokenInput")
        self.hboxlayout.addWidget(self.botTokenInput)
        self.testTokenButton = QtWidgets.QPushButton(parent=self.groupToken)
        self.testTokenButton.setObjectName("testTokenButton")
        self.hboxlayout.addWidget(self.testTokenButton)
        self.mainLayout.addWidget(self.groupToken)
        self.groupChannel = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupChannel.setObjectName("groupChannel")
        self.hboxlayout1 = QtWidgets.QHBoxLayout(self.groupChannel)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.channelInput = QtWidgets.QLineEdit(parent=self.groupChannel)
        self.channelInput.setObjectName("channelInput")
        self.hboxlayout1.addWidget(self.channelInput)
        self.testChannelButton = QtWidgets.QPushButton(parent=self.groupChannel)
        self.testChannelButton.setObjectName("testChannelButton")
        self.hboxlayout1.addWidget(self.testChannelButton)
        self.mainLayout.addWidget(self.groupChannel)
        self.groupCount = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupCount.setObjectName("groupCount")
        self.hboxlayout2 = QtWidgets.QHBoxLayout(self.groupCount)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.memberCountInput = QtWidgets.QSpinBox(parent=self.groupCount)
        self.memberCountInput.setMinimum(0)
        self.memberCountInput.setMaximum(50000)
        self.memberCountInput.setProperty("value", 0)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.memberCountInput.setFont(font)
        self.memberCountInput.setObjectName("memberCountInput")
        self.hboxlayout2.addWidget(self.memberCountInput)
        self.mainLayout.addWidget(self.groupCount)
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.hboxlayout3.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.hboxlayout3.addWidget(self.stopButton)
        self.mainLayout.addLayout(self.hboxlayout3)
        self.groupStats = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupStats.setObjectName("groupStats")
        self.gridLayout = QtWidgets.QGridLayout(self.groupStats)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdTotalMembers = QtWidgets.QLCDNumber(parent=self.groupStats)
        self.lcdTotalMembers.setDigitCount(8)
        self.lcdTotalMembers.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.lcdTotalMembers.setObjectName("lcdTotalMembers")
        self.gridLayout.addWidget(self.lcdTotalMembers, 0, 0, 1, 1)
        self.lcdRemovedMembers = QtWidgets.QLCDNumber(parent=self.groupStats)
        self.lcdRemovedMembers.setDigitCount(8)
        self.lcdRemovedMembers.setObjectName("lcdRemovedMembers")
        self.gridLayout.addWidget(self.lcdRemovedMembers, 0, 1, 1, 1)
        self.lcdTimer = QtWidgets.QLCDNumber(parent=self.groupStats)
        self.lcdTimer.setDigitCount(10)
        self.lcdTimer.setObjectName("lcdTimer")
        self.gridLayout.addWidget(self.lcdTimer, 0, 2, 1, 1)
        self.labelTotal = QtWidgets.QLabel(parent=self.groupStats)
        self.labelTotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTotal.setObjectName("labelTotal")
        self.gridLayout.addWidget(self.labelTotal, 1, 0, 1, 1)
        self.labelRemoved = QtWidgets.QLabel(parent=self.groupStats)
        self.labelRemoved.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelRemoved.setObjectName("labelRemoved")
        self.gridLayout.addWidget(self.labelRemoved, 1, 1, 1, 1)
        self.labelTimer = QtWidgets.QLabel(parent=self.groupStats)
        self.labelTimer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTimer.setObjectName("labelTimer")
        self.gridLayout.addWidget(self.labelTimer, 1, 2, 1, 1)
        self.mainLayout.addWidget(self.groupStats)
        self.groupLog = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupLog.setObjectName("groupLog")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.groupLog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.logDisplay = QtWidgets.QTextEdit(parent=self.groupLog)
        self.logDisplay.setReadOnly(True)
        self.logDisplay.setObjectName("logDisplay")
        self.vboxlayout.addWidget(self.logDisplay)
        self.mainLayout.addWidget(self.groupLog)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telegram Channel Members Remover By https://erfan4lx.com"))
        MainWindow.setWindowIcon(QtGui.QIcon("icon.jpg"))
        self.groupToken.setTitle(_translate("MainWindow", "Bot Token"))
        self.botTokenInput.setPlaceholderText(_translate("MainWindow", "  123456789:AAFxxxxxxxxxxxxxxxxxxxxxxxxxxxx"))
        self.testTokenButton.setText(_translate("MainWindow", "Test Token"))
        self.groupChannel.setTitle(_translate("MainWindow", "Target Channel / Group"))
        self.channelInput.setPlaceholderText(_translate("MainWindow", "  -1001234567890 or @channelname"))
        self.testChannelButton.setText(_translate("MainWindow", "Test Access"))
        self.groupCount.setTitle(_translate("MainWindow", "Members to Remove"))
        self.startButton.setText(_translate("MainWindow", "▶ START CLEANING"))
        self.stopButton.setText(_translate("MainWindow", "■ STOP"))
        self.groupStats.setTitle(_translate("MainWindow", "Operation Stats"))
        self.labelTotal.setText(_translate("MainWindow", "Total Members"))
        self.labelRemoved.setText(_translate("MainWindow", "Removed"))
        self.labelTimer.setText(_translate("MainWindow", "Elapsed Time"))
        self.groupLog.setTitle(_translate("MainWindow", "Operation Log"))
        self.logDisplay.setPlaceholderText(_translate("MainWindow", "Log output will appear here..."))
